# Defaults are configured in /etc/sysctl.d/* and can be customized in this file

net.bridge.bridge-nf-call-arptables = 0
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0

net.ipv4.tcp_congestion_control=bbr
net.ipv4.tcp_notsent_lowat=1572864 

net.core.netdev_budget = 300
net.core.netdev_budget_usecs = 30000
net.core.netdev_max_backlog = 20000

net.core.dev_weight = 32
net.core.dev_weight_rx_bias = 1
net.core.dev_weight_tx_bias = 2

# Basic memory and net core config
vm.min_free_kbytes=24576
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 10

#fs.file-max = 51200
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.somaxconn = 4096
net.core.rps_sock_flow_entries = 0

net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 600
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 4096
net.ipv4.tcp_max_tw_buckets = 16384
net.ipv4.tcp_rmem = 4096 87380 8388608
net.ipv4.tcp_wmem = 4096 65536 8388608

#net.ipv4.neigh.default.gc_thresh3=1024 #default:1024
#vm.vfs_cache_pressure = 100 #default: 100
vm.swappiness=15 #default: 60
